### ISSUE TITLE
expanding the naughty words list

### ISSUE THREAD

**Issue by imnotakopp** [WireHallMedic/LoreBotPy#1]
Reviewed pypi and think you could use https://pypi.org/project/profanity-check/ which is a trained model to determine if a word is naughty. Just looking to bump my counts ;)

**Comment by WireHallMedic** [comment]
Closing as won't fix, there needs to be an overwhelming use case to include trained models. 
Additionally, from the documentation:
> Never treat any prediction from this library as unquestionable truth, because it does and will make mistakes. Instead, use this library as a heuristic.
